### PR TITLE
New GSH beta: Added functions (sort of)

### PR DESCRIPTION
**Pull request by Dandigit**
## Info
This PR adds `gsh-beta.py` which is an experimental version of GSH. This version has functions partially implemented, with a few flaws:
- String literals cannot be passed as parameters, they must first be assigned to variables
- Number literals can be passed as parameters, but inconsistencies occur

A reminder on the function syntax:

## Examples
**Function definition**
```
gsh > fn foo {x, y, z} (
gsh ^ print <- uppercs <- x
gsh ^ print <- lowercs <- y
gsh ^ print <- indln <- z
gsh ^ )
```
**Function call**
```
gsh > p1 <- "lol"
gsh > foo <- p1, p1, p1
```
## Before merging
- [x] Add basic function class
- [x] Add function definition parser
- [x] Add function call parser

### CODE REVIEW

**Comment by SimpleBinary** [comment]
@Dandigit What do you mean by inconsistencies in the numbers?

**Comment by Dandigit** [comment]
It's inconsistent in that I can do this:
```
doSomething <- 2, 2
```
but not this:
```
doSomething <- 2, "str"
```
So really it's the string inconsistencies __causing__ the number inconsistencies.

**Comment by SimpleBinary** [comment]
Oh, well, its a good start. I'm going to work on a few things too. I have finished the info page [here.](https://simplebinary.github.io/GWN.html)

**Comment by Dandigit** [comment]
Yeah I saw that! It looks pretty good, a nice little summary of GWN.

**Comment by SimpleBinary** [comment]
@Dandigit Should I make a new branch to add to so you can easily edit your branch?

**Pull request merged**
